### ISSUE TITLE
Mempool buy problem

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#19]
Sukiyaki Mempool Buy

Fail Reason: 

insufficient funds for gas * price + value
Kept getting Trade Disabled, even though I had Auto-Gas Limit.

63e3c8d365e52dabbf3d556e
63e3c6b7b8cb40932151411c
63e3cc22b8cb409321514121
63e3c897f0e176d576361543

**Comment by icex** [comment]
Don't use autogas on mempool, it is technically impossible to detect when trading is disabled.  We should disable autogas option if mempool is enabled

**Comment by DDbullet** [comment]
First time i hear this, didn't knew. So yeah, better to disable it.

**Comment by icex** [comment]
When mempool is enabled, auto gas limit is disabled in the UI now.
