### ISSUE TITLE
when you open a snipe if you keep selected the Bullet Router it asks how many wallets

### ISSUE THREAD

**Issue by cozoplean** [TradersClubB/bullet-app#25]
when you open a snipe if you keep selected the Bullet Router it asks how many wallets even if 1 is selected.

**Comment by icex** [comment]
where? screenshot?

**Comment by icex** [comment]
Unable to reproduce this issue. Make sure your cache is cleared in your browser and test it without buying by not adding a amount value.

<img width="599" alt="Screenshot 2023-02-20 at 14 54 35" src="https://user-images.githubusercontent.com/2853554/220114369-92d84198-95f2-4a3b-ae6b-16a61d249006.png">
