### ISSUE TITLE
Alpha didn't detected taxes changes and info's

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#30]
![taxes](https://user-images.githubusercontent.com/124812952/219856792-5c26c433-ed0c-4e7d-b9f1-7be2a7ed2647.jpg)

**Comment by icex** [comment]
order id?

**Comment by DDbullet** [comment]
There isn't a order id since we didn't tried to buy or sell, we just pasted the CA and it didn't returned the info it should return

**Comment by icex** [comment]
Looks like it is working now after the last update

Buy Tax
5%
Sell Tax
5.2%
Buy gas used
191086 Gwei
Sell gas used
307961 Gwei
Max TX
n/a SETM
Max Wallet
n/a SETM

Edit: it doesn't if the token is not present in the db only after the second try

**Comment by icex** [comment]
fixed
