### ISSUE TITLE
Error mempool launch alpha

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#32]
Tx: https://etherscan.io/tx/0x2a3204c6ba38481b92ad8a4694d35add87310c3c6c7d663f8264a0572e7ba831
Order id: 63f395f9504d366322224aa6

Tx: https://etherscan.io/tx/0x3002d8857b8245657fcdabda21091f719cce9d8e7770cadfafec027fcc5aa166
Order id: 63f3958888f56da46360e4ed

**Comment by icex** [comment]
fixed.
