### ISSUE TITLE
token is seen as HP and it is not

### ISSUE THREAD

**Issue by cozoplean** [TradersClubB/bullet-app#33]
<img width="2228" alt="Screenshot 2023-02-20 at 23 12 28" src="https://user-images.githubusercontent.com/98698751/220199287-9c9da01a-d25f-4de0-87fb-1e9f38b3252c.png">
<img width="244" alt="Screenshot 2023-02-20 at 23 12 34" src="https://user-images.githubusercontent.com/98698751/220199301-467ef51e-3f8e-4cce-b50c-3fc4cce7d9e0.png">

this token: 0x3680FDD6CeE72806794acAdbaFF0bd81EcCfE886
is seen as HP

**Comment by icex** [comment]
Not alpha bug. Same behavior on bullet.  Token probably has cooldown or maxwallet/maxtx that is not detected properly
has Cooldown
                // at launch if the transfer delay is enabled, ensure the block timestamps for purchasers is set -- during launch.
                if (transferDelayEnabled){
                    if (to != address(dexRouter) && to != address(lpPair)){
                        require(_holderLastTransferTimestamp[tx.origin] < block.number - 2 && _holderLastTransferTimestamp[to] < block.number - 2, "_transfer:: Transfer Delay enabled.  Try again later.");
                        _holderLastTransferTimestamp[tx.origin] = block.number;
                        _holderLastTransferTimestamp[to] = block.number;
                    }
                }

Same result here
https://honeypot.is/ethereum?address=0x3680FDD6CeE72806794acAdbaFF0bd81EcCfE886
