### ISSUE TITLE
Bullet router - bug?

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#42]
![github](https://user-images.githubusercontent.com/124812952/220712779-43c0ad46-88c2-4fac-a324-73914207b9b7.jpg)

I've set it up to buy 0.1 eth with bullet router, he bought on 4 wallets

order id; 63f649b80edacfdf1dd8e2ac

**Comment by icex** [comment]
changed the behaviour in alpha. check if it works
