### ISSUE TITLE
Max tx - bug

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#49]
So, this token: 0xc358fc6810e2801f65f82dc82232dccae7e6f934

![maxtx](https://user-images.githubusercontent.com/124812952/221730375-8c34b4ab-432c-46a3-bab9-d059e774ce7f.jpg)
 
 It appears as it has a max tx, but i was checking the deployer and he actualy removed limits here:
 https://etherscan.io/tx/0x8178e697ecbe9a8571284db2cd739a46995ccf5f08cfc81d0038aecacaec45a7
 
 I was trying to buy bigger, but bullet capped my buy at that max tx, seconds after me a mev bot bought 15 eth. So yeah. Probably a bug.

**Comment by icex** [comment]
A limitation on how max tx detection currently works.
