### ISSUE TITLE
Bullet didn't triggered the buy BSC mempool

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#50]
Order id:

6400d2eaa7a88ea4e176051a
![proof](https://user-images.githubusercontent.com/124812952/222503597-a3d4d88b-9ccc-42d0-9ea0-9e36ce0cb37f.jpg)

**Comment by DDbullet** [comment]
Chart is live for 15 minutes, i still get HP detected and no stuff.

**Comment by icex** [comment]
fixed
