### ISSUE TITLE
Mempool buy problem, AGAIN

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#54]
6402701ecebb763bf67c5773

![chartscrypto](https://user-images.githubusercontent.com/124812952/222840570-193e4481-7ba6-45ab-99fe-1e150715a7f3.jpg)

I used heuristic, bullet was triggered by 2 tx'es, but didn't bought on the 3rd wich was enable trading or whatever

**Comment by icex** [comment]
6402701ecebb763bf67c5773
 order not found...
