### ISSUE TITLE
Mempool fail eth

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#61]
6407a51f3c9f9a4b9f5945cb

6407a8915176cfaa4c206f45

**Comment by icex** [comment]
for 6407a51f3c9f9a4b9f5945cb 
1st error Trading is not active.
1nd error out of gas .. make sure you set a high gas limit 

for 6407a8915176cfaa4c206f45
 EXCESSIVE_INPUT_AMOUNT -> need to check/adjust input amount on max tx limit

**Comment by icex** [comment]
This was fixed later on
