### ISSUE TITLE
Mempool always reverse first tx

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#69]
Mempool always reverse first tx

Id's to check:
1 - 642b442fc0b4c8df2319d9cb
2 - 642b4593c0b4c8df2319d9cd
3 - 642b106cc0b4c8df2319d9bf
4 - 642b227fd6b51ffb4d992eba

Some of them i was using 90 slippage without router, then you told me to use router and 100 slippage wich i did and still got that error.

I posted just 4 of them with all the scenarios so you can look into them.

**Comment by icex** [comment]
1 - 642b442fc0b4c8df2319d9cb slippage error. should be 0 - Buying Token $VDOGE with slippage 100% (136300.0 $VDOGE)
2 - 642b4593c0b4c8df2319d9cd INSUFFICIENT_LIQUIDITY too early, heuristic buy attempt.  your add liq buy tx is actualy 0x6489d5ed7627495f521168a691fa42e54231fcdb6ec79f59d225207840c96017
3 - 642b106cc0b4c8df2319d9bf  slippage error (maybe 99% tax?)
4 - 642b227fd6b51ffb4d992eba  - **TOKEN: Max Transaction Limit** - auto max tx is not calculated for 100% slippage.
