### ISSUE TITLE
HP checker works even if it's disabled

### ISSUE THREAD

**Issue by ValdemarCrypto** [TradersClubB/bullet-app#7]
Order id: 62aca4c732754da9a401a141

Settings:
Contract to snipe: https://bscscan.com/token/0x872360c5ff23afbe0f484abbdce2a087313f6151
HP checker: disabled

Buy has failed with status: "Buy State Trade Disabled"
Token was detected as a honeypot. This was caused because of PinkAntibot. It was configured to allow only 1 transaction for 1 wallet withing the first 5 minutes. So that's why I disabled HP checker to buy it anyway. Bot sniper did not buy.

**Comment by TradersClubB** [comment]
Fixed
