### ISSUE TITLE
order 6444f0ed3e01f92f40b5483c

### ISSUE THREAD

**Issue by cozoplean** [TradersClubB/bullet-app#70]
all three successful buys, but no tokens get into user's wallet.

**Comment by icex** [comment]
https://etherscan.io/token/0x1EaBa44174f5a9eA0434D6177bd813B335552d4f?a=0xF7c9a5bd7B9DF25b110E4199816310768467F7B4

https://etherscan.io/token/0x1EaBa44174f5a9eA0434D6177bd813B335552d4f?a=0x3bd052c0ACDB1aF6fB6313EBD57C2465E987AA2a

he used bullet router with multi wallets

**Comment by icex** [comment]
And also split 3 txs..
