### ISSUE TITLE
Mempool buy fail

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#72]
64512d0096c5bfd949d37647

I used the enable trade id, 100% slippage and got reverted at launch.

**Comment by Cryptolord123** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by icex** [comment]
search:
64512d0096c5bfd949d37647

No orders found..
