### ISSUE TITLE
Insufficient output amount with 99.999 slip

### ISSUE THREAD

**Issue by citronfruit** [TradersClubB/bullet-app#73]
Not sure what is happening here, I had multiple times this error insufficient output amount with a slip of 99.999%, here are multiple orders where I got this error

6451559de4a8ffe8e1d38abb
644f8b4630068c462aaf3f45
644d0e603ae5f3e92abea578

I have seen that very often, it happens when the launch function is simply add lp

**Comment by icex** [comment]
6451559de4a8ffe8e1d38abb -> this has been fixed 3 days ago
