### ISSUE TITLE
Addliq did not trigger on mempool method id snipe

### ISSUE THREAD

**Issue by citronfruit** [TradersClubB/bullet-app#78]
6461d7f253008c525db7215a

I sniped this token that had an enable trading of which I put the method id. However, the dev used the enable before the add liq, when he added liquidity 3 minutes later, I did not trigger the add liq and it bought block 1

**Comment by icex** [comment]
We will add a separate toggle switch for add Liq option

**Comment by icex** [comment]
added in alpha branch for testing
