### ISSUE TITLE
HP checker and taxes limits are correlated 

### ISSUE THREAD

**Issue by ValdemarCrypto** [TradersClubB/bullet-app#8]
According to conversation with Sly in the TG, HP checker has nothing to do with tax limits. But when you disable HP checker, you are not able to change tax limits. Also when you enable mempool buy, HP checker is disabled by default and therefore tax limits are disabled in the UI and not changeable, but they are still being checked.

**Comment by TradersClubB** [comment]
When mempool is enabled HP checker is disabled when buying(cannot check with mempool). Taxes are detected by HP checker.

**Comment by ValdemarCrypto** [comment]
Ok
