### ISSUE TITLE
Mempool fail - with 99% slippage + method id

### ISSUE THREAD

**Issue by DDbullet** [TradersClubB/bullet-app#87]
I've used 99 slippage + method id on this one: 

64691d7911e2137780cab143

I've got first tx reverted. 

All of the buys were above of what i want to buy.

**Comment by icex** [comment]
Trading Not enabled

https://dashboard.tenderly.co/tx/mainnet/0x8d8ef96934a3c300cb761f5175299e8b3d936f317938fea21c488c35ae39528b

**Comment by icex** [comment]
If you used profiles, make sure you save them again (with the Add liq option), otherwise it will default to enabled
